version: "2"
services:
  freenote-client:
    build: ./client
    ports:
      - '3000:3000'
  freenote-server:
    depends_on: 
      - 'freenote-database'
    build: './server'
    ports:
      - '4000:4000'
  freenote-database:
    image: 'mongo:latest'
    environment:
      - AUTH=no
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles -logpath=/dev/null