version: "2"
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
  server:
    depends_on: 
      - 'mongo'
    build: './server'
    ports:
      - '4000:4000'
  mongo:
    image: 'mongo:latest'
    ports:
      - 27017